services:
  web:
    build: .
    environment:
      - ORT_PROVIDER=CPUExecutionProvider
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: face_swap
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
